# Generated by Django 5.2.17 on 2026-09-28 09:41

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('capacity', models.PositiveIntegerField()),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('image', models.URLField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
