# Generated by Django 5.2.17 on 2026-09-29 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='status',
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.venue'),
        ),
        migrations.AddField(
            model_name='registration',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Technical', 'Technical'), ('Cultural', 'Cultural'), ('Sports', 'Sports'), ('Workshop', 'Workshop'), ('Academic', 'Academic'), ('Social', 'Social'), ('Seminar', 'Seminar')], max_length=20),
        ),
    ]
