# Generated by Django 5.2.17 on 2026-10-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_image_alter_venue_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='connect_opt_in',
            field=models.BooleanField(default=False),
        ),
    ]
