# Generated by Django 5.2.17 on 2026-10-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_feedback_rating_content_feedback_rating_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_verified_organizer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
