# Generated by Django 6.1.1 on 2026-10-06 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_event_deleted_at_event_is_archived_event_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='event',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feedback',
            name='organizer_reply',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
